FAQ - update 'battery' entry
corona-warn-app/cwa-website pull request #1084
Opened 2021-04-13 12:00 UTC by heinezen

Changelog:
- Update instruction list formatting
- Make the 3rd paragraph more clear
- lasst sentence: add "wenn sie denken, dass" (german)

2021-04-13 18:15 UTC, MikeMcC399 commented on src/data/faq_de.json
> +                            "Bitte beachten Sie bei der Interpretation Ihres Akkuverbrauchs, dass sich die angezeigte Prozentangabe des Akkuverbrauchs der Corona-Warn-App relativ zum Verbrauch aller
"Wenn Sie ihr Telefon ..." =>
Wenn Sie Ihr Telefon ..."

2021-04-13 18:16 UTC, MikeMcC399 requested changes
Just one typo noted from the original text.

2021-04-15 12:32 UTC, heinezen commented on src/data/faq_de.json
> +                            "Bitte beachten Sie bei der Interpretation Ihres Akkuverbrauchs, dass sich die angezeigte Prozentangabe des Akkuverbrauchs der Corona-Warn-App relativ zum Verbrauch aller
fixed

2021-04-22 09:25 UTC, dsarkar approved these changes

2021-04-22 09:30 UTC, dsarkar commented
![image](https://user-images.githubusercontent.com/1409741/115691171-1638b300-a35e-11eb-8d49-551446339004.png)

2021-04-22 09:30 UTC, dsarkar commented
![image](https://user-images.githubusercontent.com/1409741/115691231-26e92900-a35e-11eb-84da-db2458d0c4f3.png)

2021-04-22 09:30 UTC, dsarkar commented
@heinezen @MikeMcC399 Thanks!

2021-04-22 09:32 UTC, merged