Fix typos in `eventregistration` & blog post
corona-warn-app/cwa-website pull request #1135
Opened 2021-04-23 18:03 UTC by Ein-Tim

This commit fixes some typos discovered by @DerVogel2020 in https://github.com/corona-warn-app/cwa-website/pull/1132#pullrequestreview-643532898.
This PR also changes "Corona warning app" to "Corona-Warn-App" in the English blog post "2021-04-23-qr-code-generator-website".

2021-04-23 18:06 UTC, MikeMcC399 commented on blog/2021-04-23-qr-code-generator-website/index.md
> +The Corona-Warn-App community provided the QR code generator to the project team on GitHub. The development team then reviewed the community's contribution and released the QR code generator in a cus
Corona-Warn-Ap => Corona-Warn-App !

2021-04-23 18:07 UTC, MikeMcC399 requested changes
There is a "p" missing in the word "App".

2021-04-23 18:09 UTC, Ein-Tim commented
Thanks!

2021-04-23 18:12 UTC, DerVogel2020 approved these changes

2021-04-24 04:17 UTC, heinezen commented
LGTM

2021-04-24 04:18 UTC, heinezen approved these changes

2021-04-24 04:18 UTC, merged

2021-04-24 08:03 UTC, dsarkar commented
@Ein-Tim @MikeMcC399 Many thanks.