fix capital letter and whitespace
corona-warn-app/cwa-website pull request #1181
Opened 2021-04-30 19:06 UTC by DerVogel2020

Capital first letter of "private Feier" as mentioned in #1179 and remove whitespace

2021-05-01 07:02 UTC, dsarkar approved these changes

2021-05-01 07:02 UTC, dsarkar commented
@DerVogel2020 Thanks.

2021-05-03 07:47 UTC, svengabr requested changes
This is not the part of the code meant for the mentioned issue. The text change in your changed paragraph is grammatically wrong.

The locationtype list should have changed instead:
```
"locationtypes": [
    { "id": "", "name": "Bitte auswählen" },
    { "id": 3, "name": "Einzelhandel" },
    { "id": 4, "name": "Gastronomiebetrieb" },
    { "id": 5, "name": "Handwerksbetrieb" },
    { "id": 6, "name": "Arbeitsstätte" },
    { "id": 7, "name": "Bildungsstätte" },
    { "id": 8, "name": "öffentliche Gebäude" },
    { "id": 1, "name": "anderer Ort" },
    { "id": 9, "name": "Kulturveranstaltung" },
    { "id": 10, "name": "Vereinsaktivität" },
    { "id": 11, "name": "private Feier" },
    { "id": 12, "name": "Gottesdienst" },
    { "id": 2, "name": "anderes Event" }
]
```

2021-05-03 07:49 UTC, svengabr commented
@DerVogel2020 I will close this one because you did already open a new pull request https://github.com/corona-warn-app/cwa-website/pull/1180

2021-05-03 07:49 UTC, closed without merging