FAQ vaccination_certificate_multiple_scan_possible
corona-warn-app/cwa-website pull request #1312
Opened 2021-05-29 10:15 UTC by dsarkar

vaccination_certificate_multiple_scan_possible

2021-05-29 21:10 UTC, Ein-Tim requested changes
Two small comments here

2021-05-29 21:10 UTC, Ein-Tim commented on src/data/faq.json
> +                            "There is no limit to how often you scan the 2D barcode (QR code) of your vaccination certificates. You can add and manage the vaccination certificates on multiple devices
```suggestion
                            "There is no limit to how often you can scan the 2D barcode (QR code) of your vaccination certificates. You can add and manage the vaccination certificates on multiple devices, on a new device, on a device you have reset, and even in several apps. Therefore, a backup is not required."
```

2021-05-29 21:10 UTC, Ein-Tim commented on src/data/faq_de.json
> +                            "Es gibt keine Begrenzung, wie oft Sie den 2D-Barcode (QR-Code) Ihres Impfzertifikats scannen. Sie können die Impfzertifikate auf mehreren Geräten, auf einem neuen Gerät,
```suggestion
                            "Es gibt keine Begrenzung, wie oft Sie den 2D-Barcode (QR-Code) Ihres Impfzertifikats scannen können. Sie können die Impfzertifikate auf mehreren Geräten, auf einem neuen Gerät, auf einem zurückgesetzten Gerät, und sogar in mehreren Apps hinzufügen und verwalten. Daher ist auch keine Sicherung (Backup) erforderlich."
```

2021-05-30 06:26 UTC, dsarkar commented
@Ein-Tim Thanks

2021-05-30 08:04 UTC, merged