Release 2.10 updates
corona-warn-app/cwa-website pull request #1730
Opened 2021-09-13 08:48 UTC by dsarkar

2021-09-13 09:03 UTC, MikeMcC399 commented on src/data/privacy.json
>              "textcaption": "Last updated: September 8th, 2021"
Last updated => Sept 22?

2021-09-13 09:18 UTC, MikeMcC399 requested changes
Dates aren't consistent between English and German versions.

2021-09-13 09:49 UTC, dsarkar commented on src/data/privacy.json
>              "textcaption": "Last updated: September 8th, 2021"
Thanks @MikeMcC399

2021-09-17 14:57 UTC, MikeMcC399 commented on src/data/screenshots-archive-2-9.json
> +                "title": "Check In - Scan QR code",
```suggestion
                "title": "Check In - Scan QR Code",
```

2021-09-17 14:57 UTC, MikeMcC399 commented on src/data/screenshots-archive-2-9.json
> +                "title": "Check In - Create QR code",
```suggestion
                "title": "Check In - Create QR Code",
```

2021-09-17 14:58 UTC, MikeMcC399 requested changes
Missing capitalization in 2.9 archive for iOS.

2021-09-17 23:04 UTC, dsarkar commented
@MikeMcC399 Thanks.

2021-09-21 14:25 UTC, Ein-Tim requested changes
Android will probably release 2.10.1: https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.10.1-RC1

2021-09-21 14:25 UTC, Ein-Tim commented on gulpfile.js
> +    .pipe(replace('[android.current-app-version]', '2.10.0'))
```suggestion
    .pipe(replace('[android.current-app-version]', '2.10.1'))
```

See https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.10.1-RC1

2021-09-22 06:44 UTC, dsarkar commented
@Ein-Tim Thanks.

2021-09-22 08:07 UTC, merged