Add english translation for analysis page.
corona-warn-app/cwa-website pull request #2079
Opened 2021-11-15 12:34 UTC by FabioFuschi-SNK

This PR adds the English translation for the analysis page.

2021-11-15 12:36 UTC, dsarkar approved these changes

2021-11-15 12:54 UTC, MikeMcC399 commented
The app and the FAQs use US English spelling, so I'm not sure if that should apply to the spelling in the analysis page.

"behaviour" is British English, whereas "behavior" would be US English.

2021-11-15 12:57 UTC, MikeMcC399 commented on src/data/analyse_en.json
> +            "desc": "Workdaily updated information on vaccination status and progress in Germany, from the website 'together against corona' from the German federal ministry of health (BMG).",
"Workdaily" should probably be "Daily", then it would match the other titles.

2021-11-15 13:04 UTC, MikeMcC399 commented on src/data/analyse_en.json
> +    		"title": "WHO: COVID 19 Dashboard (EN)",
Suggest
"COVID 19" => "COVID-19"

to match the text on the website https://covid19.who.int/ itself.

2021-11-15 13:08 UTC, MikeMcC399 commented on src/data/analyse_en.json
> +                "content": "<strong>Sharing behaviour</strong><p>Count of positive test results, for which a QR code was registered or a teleTAN requested for validation, as well as the sum of positi
"Corona warning app" => "Corona-Warn-App"

2021-11-15 13:11 UTC, MikeMcC399 commented on src/data/analyse_en.json
> +            "timerange": "Timerange",
"Timerange" => "Time range"

2021-11-15 13:12 UTC, MikeMcC399 commented on src/data/analyse_en.json
> +    "lang": "en-UK",
Shouldn't this be "en-GB"?

2021-11-15 13:14 UTC, MikeMcC399 requested changes
Everything works!

I just made a few comments suggesting text changes.

I noticed that the date appears in US format, not European English format with 

dd/mm/yyyy.

Maybe this is linked to the lang definition which is set to "en-UK"?

2021-11-16 10:42 UTC, FabioFuschi-SNK commented
> Everything works!
> 
> I just made a few comments suggesting text changes.
> 
> I noticed that the date appears in US format, not European English format with
> 
> dd/mm/yyyy.
> 
> Maybe this is linked to the lang definition which is set to "en-UK"?

@MikeMcC399 Thank you for the hint, i changed the date format to GB date format now. 

I have also changed the wording of the mentions in the English translation

2021-11-16 16:25 UTC, MikeMcC399 commented
@FabioFuschi-SNK 
Thank you for the changes! Would you like to mark each of them as resolved? (See https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request). That makes it easier for you, me and anybody else reading this PR.

2021-11-16 16:29 UTC, MikeMcC399 commented on src/data/analyse_en.json
> +            "desc": "Daily updated information on vaccination status and progress in Germany, from the website 'together against corona' from the German federal ministry of health (BMG).",
"federal ministry of health" should be capitalized:

Federal Ministry of Health

Reference:
https://www.bundesgesundheitsministerium.de/en/legal-notice.html

2021-11-16 16:29 UTC, MikeMcC399 requested changes
The Federal Ministry of Health (Bundesministerium für Gesundheit, BMG)

should be capitalized.

2021-11-17 11:03 UTC, MikeMcC399 approved these changes
@FabioFuschi-SNK 

This looks good to publish now! 👍🏻

2021-11-17 11:12 UTC, MikeMcC399 commented
See also https://github.com/corona-warn-app/cwa-website/issues/2091 and for `/en/analysis/`:

"Last data update: November 17, 2021, 9:21 AM GMT+1. The data of the CWA dashboard is updated on a daily basis at 10:30 AM."

I don't think that this minor issue about the timestamp differences should stop the English page being published though.

2021-11-18 07:47 UTC, dsarkar commented
@FabioFuschi-SNK Many thanks for providing the PR.
@MikeMcC399  Many thanks for the review!

2021-11-18 07:49 UTC, merged

2021-11-18 13:45 UTC, MikeMcC399 commented
Now listed on Twitter:
https://twitter.com/coronawarnapp/status/1461311095688290309?s=20 🙂