Release 2.14 Screenshots
corona-warn-app/cwa-website pull request #2085
Opened 2021-11-16 05:54 UTC by larswmh

EN:
![image](https://user-images.githubusercontent.com/88365935/141928680-c97e1113-6ab4-4cf0-bcf3-9a9d9b716d03.png)
![chrome_QzPixMTOyZ](https://user-images.githubusercontent.com/88365935/141928789-33b5f7e8-5776-4946-8804-414efc53ef88.png)

DE:
![image](https://user-images.githubusercontent.com/88365935/141928718-2e4ef8df-2506-4f40-9790-f57665af0b5c.png)
![chrome_fU30UzZMPX](https://user-images.githubusercontent.com/88365935/141928804-8f5774e5-da8a-4cf4-9bf0-4a0198607e47.png)

2021-11-17 14:02 UTC, dsarkar approved these changes

2021-11-21 15:36 UTC, MikeMcC399 requested changes
Grammar suggestion for German text.

2021-11-21 15:36 UTC, MikeMcC399 commented on src/data/screenshots_de.json
> +                "<b>Papierkorbfunktion für Tests:</b> Sie können in der App Schnelltests und PCR-Tests nach dem Löschen wiederherstellen. Sie haben somit die Möglichkeit Objekte die sie versehentlich
```suggestion
                "<b>Papierkorbfunktion für Tests:</b> Sie können in der App Schnelltests und PCR-Tests nach dem Löschen wiederherstellen. Sie haben somit die Möglichkeit, Objekte, die Sie versehentlich gelöscht haben, wiederherzustellen.",
```

Check with https://mentor.duden.de/.

2021-11-22 06:14 UTC, dsarkar commented
Good Morning @MikeMcC399 ! Thanks.

2021-11-22 06:14 UTC, merged