Update backup for analyseData.json
corona-warn-app/cwa-website pull request #2131
Opened 2021-11-26 15:00 UTC by brifemu

In this PR due to today's technical issue, I have made a change on the server deploy, updating the backup file used to start the project in localhost without internet connection.

The file had been added to the .gitignore file because for testing is not necessary to keep the file updated, just is important for the deployed site.

The file name was changed because IDK why, with the last name .gitignore ignored ignore the file.

2021-11-26 15:07 UTC, dsarkar approved these changes

2021-11-26 15:41 UTC, MikeMcC399 requested changes
@brifemu
When I execute
`npm run build`
in this branch, it creates an untracked file
`src/data/analyse_data_no_internet.json`

so I think something needs to change in this PR.

`npm run build` should not cause any changes that git status would report about.

2021-11-29 07:32 UTC, brifemu commented
> @brifemu When I execute `npm run build` in this branch, it creates an untracked file `src/data/analyse_data_no_internet.json`
> 
> so I think something needs to change in this PR.
> 
> `npm run build` should not cause any changes that `git status` would report about.

You are right. I forgot to change the path, sorry. Already fixed.

2021-11-29 08:40 UTC, MikeMcC399 commented
@brifemu 
There is no problem with `git status` now, after your latest change. 🙂

2021-11-29 09:15 UTC, svengabr approved these changes

2021-11-29 16:26 UTC, merged