Isolation Glossary
corona-warn-app/cwa-website pull request #2196
Opened 2021-12-15 12:46 UTC by browkin

- Added Isolation to Glossary
- Linked each other

<img width="496" alt="glossar1" src="https://user-images.githubusercontent.com/84206644/146188807-b07850f1-a0d6-4029-9cd7-2083bf039312.PNG">
<img width="521" alt="glossar2" src="https://user-images.githubusercontent.com/84206644/146188811-2f6d8eaf-31c4-40ed-8b76-e147d5ad09df.PNG">

RKI Link for 'Kriterien' in Isolation : https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Entlassmanagement.html?nn=13490888

2021-12-15 13:23 UTC, MikeMcC399 commented
@browkin 
Will you add an English translation?

If there is no English text available, then perhaps add the terms
- Isolation 
- Quarantine

to the English glossary and link to the German glossary with a note that the definitions are only available in German?

2021-12-16 10:34 UTC, dsarkar commented
@MikeMcC399 FYI EN texts been added.

2021-12-16 10:51 UTC, MikeMcC399 commented on src/data/faq.json
> +                    "description": "Isolation is a government-ordered measure for persons who have been confirmed to have SARS-CoV-2 infection by a PCR-Test.Isolation can be gone through at home or,
Whitespace corrections:

```suggestion
                    "description": "Isolation is a government-ordered measure for persons who have been confirmed to have SARS-CoV-2 infection by a PCR-Test. Isolation can be gone through at home or, if the disease is severe, in a hospital. Release from isolation is based on specified <a href='https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Entlassmanagement.html?nn=13490888'> criteria (German only)</a>. At the time of release, the person is considered to no longer be infectious. See also <a href='#glossary_quarantine'>Quarantine</a>. "
```

2021-12-16 10:52 UTC, MikeMcC399 requested changes
Inline suggestions to correct whitespace.

2021-12-16 10:56 UTC, MikeMcC399 commented
@dsarkar 
> FYI EN texts been added.

Thanks for the heads-up! The text looks fine, just minor formatting to be fixed.

2021-12-16 10:59 UTC, dsarkar approved these changes

2021-12-16 10:59 UTC, dsarkar commented
@MikeMcC399 Thanks for the review and corrections.

2021-12-16 11:37 UTC, merged