changed times for contact numbers
corona-warn-app/cwa-website pull request #2295
Opened 2022-01-07 14:49 UTC by browkin

- changed the times for the contact numbers in the faq

2022-01-07 15:19 UTC, dsarkar commented
closes https://github.com/corona-warn-app/cwa-website/issues/2294

2022-01-07 16:27 UTC, MikeMcC399 commented
https://github.com/corona-warn-app/cwa-website/issues/2294#issuecomment-1007542853 contains screenshots from 2.16.0-RC6 for comparison.

- https://www.coronawarn.app/en/faq/#who_can_help and
- https://www.coronawarn.app/de/faq/#who_can_help

should also be changed.

2022-01-10 09:28 UTC, Ein-Tim requested changes
Add "German"

2022-01-10 09:28 UTC, Ein-Tim commented on src/data/faq.json
> +                            "The TAN hotline will help you to enter the TAN if you have a positive PCR test result and if you have not received a TAN or document with a PCR-Test QR code. The TAN hotl
```suggestion
                            "The TAN hotline will help you to enter the TAN if you have a positive PCR test result and if you have not received a TAN or document with a PCR-Test QR code. The TAN hotline is available Monday to Sunday from 7 a.m. to 8 p.m. German local time (except on German national holidays)",
```

2022-01-10 09:28 UTC, Ein-Tim commented on src/data/faq.json
> +                            "The TAN hotline (<a href='#international_phone_numbers' target='_blank' >click here to see the phone numbers</a>) will help you to enter the TAN if you have a positive PC
```suggestion
                            "The TAN hotline (<a href='#international_phone_numbers' target='_blank' >click here to see the phone numbers</a>) will help you to enter the TAN if you have a positive PCR test result and if you have not received a TAN or document with a PCR-Test QR code. The TAN hotline is available Monday to Sunday from 7 a.m. to 8 p.m. German local time (except on German national holidays). The call is free of charge from within Germany.",
```

2022-01-10 09:30 UTC, MikeMcC399 commented
@browkin 

According to the Android app 2.16.0-RC6 the technical hotline is still reachable until 10 PM (22:00 Uhr).

See https://github.com/corona-warn-app/cwa-website/issues/2294#issuecomment-1007542853

---
Three-dot icon > App-Informationen > Technische Hotline

![Technische Hotline](https://user-images.githubusercontent.com/66998419/148573738-405e9f77-1fc6-40bf-af00-4f6e7b27f09b.png)

@dsarkar should confirm

2022-01-10 09:38 UTC, browkin commented on src/data/faq.json
> +                            "The TAN hotline (<a href='#international_phone_numbers' target='_blank' >click here to see the phone numbers</a>) will help you to enter the TAN if you have a positive PC
@Ein-Tim Thank you! Added.

2022-01-10 09:40 UTC, Ein-Tim commented
@dsarkar Can you confirm that in the future, the TAN hotline will be available for a shorter amount of time than the technical hotline?

2022-01-10 10:03 UTC, dsarkar commented
@Ein-Tim I forwarded the question. Stand by for answer.

2022-01-10 13:57 UTC, dsarkar commented
Times are confirmed: No change regarding technical hotline, and TAN hotline will be the hour as shown above.

2022-01-10 13:58 UTC, Ein-Tim commented
@dsarkar Thanks, okay.

2022-01-10 14:00 UTC, MikeMcC399 commented
@dsarkar 
Did you find out the date that the change to the TAN hotline opening hours is planned to take place? Is it on the day that 2.16 is released or some other day?

2022-01-10 15:09 UTC, dsarkar commented
@Ein-Tim @MikeMcC399 Change will come into effect on 16.01.2022. I have further information about the decision process.

2022-01-10 18:24 UTC, MikeMcC399 commented
@dsarkar 
based on ...
> Times are confirmed: No change regarding technical hotline, and TAN hotline will be the hours as shown above.

and
>  Change will come into effect on 16.01.2022.

this PR could come out of draft status. It looks now to correspond to the above.

I guess you would leave it with the label "On hold" or "do not merge" until Jan 16, 2022?

2022-01-11 08:11 UTC, MikeMcC399 commented
- I suggest to change the title of this PR to include the phrase "TAN hotline" so it is clear what phone number is affected.

- I suggested this also in issue https://github.com/corona-warn-app/cwa-website/issues/2294

2022-01-11 11:56 UTC, browkin commented on src/data/faq.json
> +                            "The TAN hotline will help you to enter the TAN if you have a positive PCR test result and if you have not received a TAN or document with a PCR-Test QR code. The TAN hotl
@Ein-Tim Thank you! added.

2022-01-11 11:57 UTC, browkin commented
continued in PR #2303 2303

2022-01-11 13:11 UTC, dsarkar commented
Should be merged 16. Jan 2021, before release of R 2.16. therefore reopen this PR and closing PR #2303

2022-01-11 13:17 UTC, dsarkar approved these changes

2022-01-16 08:29 UTC, merged