FAQ recovery certificate valid time update
corona-warn-app/cwa-website pull request #2410
Opened 2022-02-04 12:00 UTC by browkin

**Deutsch**
**Zusammenfassung der Änderungen:**

_"Wie lange ist mein Zertifikat gültig?"_
Old: "Bei einem​ Genesenenzertifikat ist die fachliche Gültigkeit laut des EU eHealth Networks festgelegt auf 'Datum des ersten positiven PCR-Test-Ergebnisses der Person' plus 180 Tage."
New: "Bei einem​ Genesenenzertifikat ist die maximale fachliche Gültigkeit laut dem RKI festgelegt auf 90 Tage."

_"Warum erhalte ich die Fehlermeldung, dass mein Zertifikat ungültig ist?"_
Old: "Ein Genesenenzertifikat darf laut Festlegung der EU dagegen nicht länger als 180 Tage ab dem Datum des letzten positiven PCR-Tests gültig sein."
New: "Ein Genesenenzertifikat darf laut einer Festlegung des Deutschen Bundestages und des Bundesrates ab dem 15. Januar 2022, dagegen nicht länger als 90 Tage ab dem Datum des letzten positiven PCR-Tests gültig sein."

**Glossar:**

_"Gültigkeit eines EU digitalen COVID-Zertifikats"_
-> "Genesenenzertifikat"
Old: "Bei einem​ Genesenenzertifikat ist die fachliche Gültigkeit laut des EU eHealth Networks festgelegt auf 'Datum des ersten positiven PCR-Test-Ergebnisses der Person' plus 180 Tage"
New: "Bei einem​ Genesenenzertifikat ist die maximale fachliche Gültigkeit laut dem RKI festgelegt auf 90 Tage."

_"Fachliche Gültigkeit"_
Old: "Bei einem​ [Genesenenzertifikat](https://www.coronawarn.app/de/faq/#glossary_recovery_certificate) ist die fachliche Gültigkeit laut des EU eHealth Networks festgelegt auf 'Datum des ersten positiven [PCR-Test](https://www.coronawarn.app/de/faq/#glossary_pcr_test)-Ergebnisses der Person' plus 180 Tage"
New: "Bei einem <a href='#glossary_recovery_certificate'>Genesenenzertifikat</a> ist die maximale fachliche Gültigkeit laut dem <a href='https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Genesenennachweis.html' target='_blank' rel='noopener noreferrer'> RKI </a> festgelegt auf 90 Tage."

**English
Changes summary:**

_"How long is my certificate valid?​"_
Old: "In the case of a recovery certificate, according to the EU eHealth Network, the effective validity is set at 'date of the holder's first positive PCR test result' plus 180 days."
New: "According to the [RKI ](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Genesenennachweis.html), the maximum effective validity of a recovery certificate is 90 days."

_"Why do I get the error message that my certificate is invalid?"_
Old: "A recovery certificate on the other hand may not be valid for longer than 180 days from the date of the last positive PCR test, as defined by the EU."
New: "A recovery certificate, however no longer than 90 days from the date of the last positive PCR test, according to a regulation of the German Bundestag and the Bundesrat since January 15, 2022."

**Glossary:**

_"Validity of an EU Digital COVID Certificate"_
-> "Recovery Certificate"
Old: "In the case of a recovery certificate, according to the EU eHealth Network, the effective validity is set at 'date of the holder's first positive PCR test result' plus 180 days"
New: "According to the [RKI ](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Genesenennachweis.html), the maximum effective validity of a recovery certificate is 90 days."

_"Effective validity"_
Old: "In the case of a [recovery certificate](https://www.coronawarn.app/en/faq/#glossary_recovery_certificate), the effective validity is set at 'date of the person's first positive [PCR test](https://www.coronawarn.app/en/faq/#glossary_pcr_test) result' plus 180 days, according to the EU eHealth Network. See also ["How long is my certificate valid?".](https://www.coronawarn.app/en/faq/#eu_dcc_validity)"
New: "According to the [RKI ](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Genesenennachweis.html), the maximum effective validity of a [recovery certificate](https://www.coronawarn.app/en/faq/#glossary_recovery_certificate) is 90 days."

2022-02-04 13:31 UTC, MikeMcC399 commented on src/data/faq.json
> -                    "description": "We refer to the duration of vaccination protection as 'effective validity'. The effective validity of the vaccination thus counts from the last vaccination date. T
This is using `markdown `syntax in a `json `file. That doesn't work.

`[recovery certificate](https://www.coronawarn.app/en/faq/#glossary_recovery_certificate)`

needs to be changed to use HTML.

2022-02-04 13:51 UTC, MikeMcC399 requested changes
Please fix the syntax error mentioned inline. It is not possible to build the web to view it.

2022-02-04 13:51 UTC, MikeMcC399 commented on src/data/faq.json
> +                            "If your certificate is technically still valid, it appears it was issued by an unauthorized body or incorrectly. In this case, we ask you to contact the <a href='#interna
There is a comma missing at the end of this line which makes the `json `invalid.

2022-02-04 13:51 UTC, MikeMcC399 commented on src/data/faq_de.json
> +                            "Ist Ihr Zertifikat technisch noch gültig, wurde es offenbar von einer nicht autorisierten Stelle oder fehlerhaft ausgestellt. In diesem Fall bitten wir Sie, sich an die <
Also here there is a comma missing at the end of the line.

2022-02-04 15:02 UTC, Ein-Tim commented
Just FYI: There are legal discussions about this change: [Verwaltungsgericht Osnabrück hält Verkürzung des Genesenenstatus auf 90 Tage für verfassungswidrig](https://www.verwaltungsgericht-osnabrueck.niedersachsen.de/aktuelles/pressemitteilungen/verwaltungsgericht-osnabruck-halt-verkurzung-des-genesenenstatus-auf-90-tage-fur-verfassungswidrig-208324.html).

2022-02-04 15:15 UTC, MikeMcC399 commented
@Ein-Tim 
Thank you very much for the link about the legal discussions. I can absolutely follow the reasoning of the court!

2022-02-07 09:24 UTC, thorbenkuro commented
Fixed the JSON-syntax error and merged the latest changes from master branch.

2022-02-07 09:57 UTC, merged

2022-02-07 10:29 UTC, MikeMcC399 commented
@dsarkar 

https://www.coronawarn.app/en/faq/#glossary_effective_validity has incorrect syntax:

![image](https://user-images.githubusercontent.com/66998419/152770580-4a04ddcb-05b3-46d2-bcbf-2245c48bb958.png)

The German language FAQ is correct

https://www.coronawarn.app/de/faq/#glossary_effective_validity

![image](https://user-images.githubusercontent.com/66998419/152770813-a4ab3d0f-f7c2-4968-9d20-1fe8cdacf15a.png)

2022-02-07 13:21 UTC, svengabr commented
@MikeMcC399 thanks, created a PR for this https://github.com/corona-warn-app/cwa-website/pull/2420