Fix for Issue 'English app download buttons on German page #2431'
corona-warn-app/cwa-website pull request #2488
Opened 2022-02-25 22:10 UTC by Crystalskulls

- Fix for Issue 'English app download buttons on German page Issue #2431'
Added german google and apple svg badges and renamed bad translated label 'App mit!' to 'App herunterladen!'

2022-02-28 10:47 UTC, MikeMcC399 commented on src/data/index_de.json
>                      "title": "Laden sie die Corona-Warn-App aus dem Apple App Store",
```suggestion
                    "title": "Laden Sie die Corona-Warn-App aus dem Apple App Store",
```

2022-02-28 10:48 UTC, MikeMcC399 commented on src/data/index_de.json
>                      "title": "Laden sie die Corona-Warn-App aus dem Google Play Store",
```suggestion
                    "title": "Laden Sie die Corona-Warn-App aus dem Google Play Store",
```

2022-02-28 10:48 UTC, MikeMcC399 requested changes
Added comment to also correct grammar in previously existing text.

2022-02-28 12:51 UTC, dsarkar commented
@Crystalskulls Thanks for the PR! Please see comments from @MikeMcC399 above!

2022-03-01 14:32 UTC, Crystalskulls commented
@dsarkar I submitted the suggestion from MikeMcC399

2022-03-01 14:34 UTC, Crystalskulls reviewed
Files reviewed

2022-03-01 14:41 UTC, MikeMcC399 approved these changes
LGTM!

2022-03-04 13:07 UTC, dsarkar approved these changes

2022-03-04 13:12 UTC, dsarkar commented
@Crystalskulls @MikeMcC399 Thanks!

2022-03-04 13:13 UTC, merged