adding dynamic sitemap to read whole pages path and title
corona-warn-app/cwa-website pull request #2504
Opened 2022-03-04 07:53 UTC by ibexad

2022-03-04 11:52 UTC, MikeMcC399 commented
@ibexad 
You should probably exclude 
```
        src/data/sitemaplist.json
        src/data/sitemaplist_de.json
```
from being committed to the repository, through `/src/data/.gitignore`, since the files are regenerated by building the web.

2022-03-04 11:52 UTC, MikeMcC399 commented
The generated sitemap is not very readable as it has only one level and shows no structure.

2022-03-04 15:14 UTC, MikeMcC399 commented
Since there are new packages added to `package.json`, I would also expect an updated `package-lock.json` to be part of this PR. 

I cannot see any changed `package-lock.json` in the PR.

2022-03-04 15:32 UTC, MikeMcC399 commented
The generated sitemap makes the inconsistent use of hyphen / en dash in `page-title` visible:

![image](https://user-images.githubusercontent.com/66998419/156789492-e54c8c5b-14e1-48dd-90b9-07c7bcb4c9ed.png)

For instance
https://github.com/corona-warn-app/cwa-website/blob/1ecd5f70d99cc3f0b65212a9b16595c467aed21d/src/pages/en/analysis/index.html#L3
uses `-`  or `U+002D` / Hyphen-Minus

whereas
https://github.com/corona-warn-app/cwa-website/blob/1ecd5f70d99cc3f0b65212a9b16595c467aed21d/src/pages/en/screenshots/index.html#L3
uses `–` or `U+2013` / En Dash

2022-03-04 15:40 UTC, MikeMcC399 commented
@ibexad 

You need to be using node 16 (see https://github.com/corona-warn-app/cwa-website/blob/master/README.md#requirements) otherwise `package-lock.json` is generated using an old version, due to the older version of `npm`.

2022-03-04 20:22 UTC, MikeMcC399 commented on src/data/sitemaplist.json
> +[
This file should be removed from the PR.

2022-03-04 20:22 UTC, MikeMcC399 commented on src/data/sitemaplist_de.json
> +[
Also this file should be removed from the PR.

2022-03-07 07:53 UTC, MikeMcC399 commented
@ibexad

It seems that this PR is still a work-in-progress. Do you want any more comments on it at this time? Perhaps if you know that you still want to make changes to it, you could convert it to draft status, so it is clear that it is not ready to be merged?

In any case I noticed various points:

1. Individual pages from `/en/science/` are not included in the sitemap. They should probably be listed.
2. The redirects, such as `/en/faq/(17).html`, are included in the sitemap although they do not point to unique content. They should be removed from the sitemap.
3. `/en/news/index.html` is a redirect to `/en/blog` so should probably be removed.
4. The screenshot archive pages, such as `/en/screenshots-archive/2-10.html` all have identical page titles, which do not include the version.
5. The sorting of the screenshot pages is in ascending order (2-10, 2-11, 2-12, 2-13, 2-14, 2-15, 2-16, 2-17, 2-2, 2-3, 2-4, 2-5, 2-6, 2-7, 2-8, 2-9) but in two groups with two-digit minor versions first, followed by one-digit minor versions. The one-digit minor versions should appear first in the list to make the sorting order consistently ascending.

Where I referred to `/en` above, the same applies to `/de`.

2022-03-08 07:46 UTC, ibexad commented
> @ibexad
> 
> It seems that this PR is still a work-in-progress. Do you want any more comments on it at this time? Perhaps if you know that you still want to make changes to it, you could convert it to draft status, so it is clear that it is not ready to be merged?
> 
> In any case I noticed various points:
> 
> 1. Individual pages from `/en/science/` are not included in the sitemap. They should probably be listed.
> 2. The redirects, such as `/en/faq/(17).html`, are included in the sitemap although they do not point to unique content. They should be removed from the sitemap.
> 3. `/en/news/index.html` is a redirect to `/en/blog` so should probably be removed.
> 4. The screenshot archive pages, such as `/en/screenshots-archive/2-10.html` all have identical page titles, which do not include the version.
> 5. The sorting of the screenshot pages is in ascending order (2-10, 2-11, 2-12, 2-13, 2-14, 2-15, 2-16, 2-17, 2-2, 2-3, 2-4, 2-5, 2-6, 2-7, 2-8, 2-9) but in two groups with two-digit minor versions first, followed by one-digit minor versions. The one-digit minor versions should appear first in the list to make the sorting order consistently ascending.
> 
> Where I referred to `/en` above, the same applies to `/de`.

Hello and thank you for your comments. 
I resolved all of them except item number 5, sorting of screenshot pages. I couldn't sort them when they are generated by gulp libraries and also handlebar has not had an option to sort the object on the page using js. Could you please take a deeper look and let me know if you find a way to do that. Thank you so much.

2022-03-08 09:33 UTC, MikeMcC399 commented
@ibexad 
Congratulations on your progress! It is good that you added version numbers to the screenshot titles. I am sorry that I don't have a solution for the screenshot version sorting. I think it is acceptable to leave it like it is now though.

I will add some other comments separately, so it is easier to respond to them.

2022-03-08 09:35 UTC, MikeMcC399 commented on src/data/sitemap_de.json
> +                "news": "Nachrichten",
The line for "science" is missing here, so there is no header for "Science" shown on `/de/sitemap/`.

2022-03-08 09:49 UTC, MikeMcC399 commented
`/de/terms-of-use/` is missing from the German `/de/sitemap/`

The file https://github.com/cuisines/cwa-website/blob/sitemap/src/pages/de/terms-of-use/index.html needs to be modified, like https://github.com/cuisines/cwa-website/blob/2c6fabc3a8fd1da6cf9e6f7bd86c81e4f49aca68/src/pages/en/terms-of-use/index.html#L6.

`page-category: About`

2022-03-08 09:50 UTC, MikeMcC399 requested changes
There are two problems on the German sitemap:

- header for Science missing
- `terms-of-use` / Nutzungsbedingungen missing

2022-03-08 11:51 UTC, ibexad commented
> 

I did not get it, could you please explain what is the issue with the german sitemap?

> There are two problems on the German sitemap:
> 
> * header for Science missing
> * `terms-of-use` / Nutzungsbedingungen missing

2022-03-08 12:26 UTC, MikeMcC399 commented on src/data/sitemap_de.json
> +                "news": "Nachrichten",
You can mark this comment as resolved now.
Thank you!

2022-03-08 12:29 UTC, MikeMcC399 commented
@ibexad 

Thank you for fixing the issues with the German sitemap. I guess your previous comment "I did not get it, could you please explain what is the issue with the german sitemap?" is now out of date.

Let me know if there is still anything unclear.

2022-03-08 15:27 UTC, MikeMcC399 commented
@ibexad 

- Will add the new pages https://www.coronawarn.app/en/accessibility/ and https://www.coronawarn.app/de/accessibility/ from PR https://github.com/corona-warn-app/cwa-website/pull/2508 to the sitemap?

2022-04-05 07:50 UTC, svengabr approved these changes

2022-04-05 08:26 UTC, merged

2022-04-05 09:25 UTC, MikeMcC399 commented
@svengabr 

After this merge, critical security vulnerabilities are reported.
`npm audit`
`43 vulnerabilities (1 low, 18 moderate, 19 high, 5 critical)`

The sitemap itself shows only a top level

![image](https://user-images.githubusercontent.com/66998419/161722987-de876446-a6a3-40ea-a6cf-27e62ad04612.png)

I'm not sure where "News" came from and the FAQ section is not listed.