Add onlinelibrary.wiley.com to allowlist
corona-warn-app/cwa-website pull request #2554
Opened 2022-03-18 16:50 UTC by brifemu

Due to issue #2490, I had included 'https://onlinelibrary.wiley.com/doi/abs/10.2307/3315826.n1' into the current allow list.

The current allow list could bring us problems in the future because we are not controlling an exact error code and if for example tomorrow this site is closed we would not get notices because the current allow list doesn't difference between 404 or 503 error.

I will create another PR in the next weeks about this, after finish the new FAQ and more pending stuff.

2022-03-18 18:24 UTC, MikeMcC399 commented
@brifemu 

I am happy to hear from you again.

I found several link running this branch so it seems that it hadn't been tested yet:

==================== Broken links ====================

```
[RESPONSE 404] http://localhost:8000/de/blog/2022-03-16-cwa-version-2-19/ on '/de/faq/' 
[RESPONSE 404] https://www.pei.de/SharedDocs/Downloads/DE/newsroom/dossiers/mindestkriterien-sars-cov-2-antigentests-01-12-2020.pdf?__blob=publicationFile&v=7 on '/de/faq/' 
[RESPONSE 404] http://localhost:8000/en/blog/2022-03-16-cwa-version-2-19/ on '/en/faq/' 
[RESPONSE 404] https://www.pei.de/SharedDocs/Downloads/DE/newsroom/dossiers/mindestkriterien-sars-cov-2-antigentests-01-12-2020.pdf?__blob=publicationFile&v=7 on '/en/faq/' 
[RESPONSE 503] https://onlinelibrary.wiley.com/doi/abs/10.2307/3315826.n1 on 'http://localhost:8000/de/blog/2021-08-05-statistictiles' 
[RESPONSE 503] https://onlinelibrary.wiley.com/doi/abs/10.2307/3315826.n1 on 'http://localhost:8000/en/blog/2021-08-05-statistictiles' 
```

I will deal with the blog and pei links separately.

2022-03-18 18:25 UTC, MikeMcC399 commented
- See issue https://github.com/corona-warn-app/cwa-website/issues/2555.

2022-03-18 19:10 UTC, MikeMcC399 commented
- See https://github.com/corona-warn-app/cwa-website/issues/2557

2022-03-19 10:24 UTC, MikeMcC399 commented on cypress/integration/check_links.js
> +      'https://onlinelibrary.wiley.com/doi/abs/10.2307/3315826.n'
```suggestion
      'https://onlinelibrary.wiley.com/doi/abs/10.2307/3315826.n1'
```

The URL was incomplete. 

- See original issue https://github.com/corona-warn-app/cwa-website/issues/2490

2022-03-19 10:29 UTC, MikeMcC399 requested changes
The allowlist URL is incomplete. See in-line comment (it should be `n1` not just `n` at the end of the URL). Note the error message for the correct URL to add to the allowlist:

`[RESPONSE 503] https://onlinelibrary.wiley.com/doi/abs/10.2307/3315826.n1 on 'http://localhost:8000/en/blog/2021-08-05-statistictiles'`

2022-03-19 10:30 UTC, MikeMcC399 commented
The Cypress test suite will run without errors if the allowlist URL in this PR is corrected and the PRs

- #2555 and
- #2557 

are merged.

2022-03-19 16:53 UTC, MikeMcC399 commented on cypress/integration/check_links.js
> +    'https://onlinelibrary.wiley.com/doi/abs/10.2307/3315826.n'
```suggestion
    'https://onlinelibrary.wiley.com/doi/abs/10.2307/3315826.n1'
```

2022-03-21 15:36 UTC, MikeMcC399 commented
@brifemu 
Thank you for correcting the allowlist URLs.
Could you please also rebase on `master` or merge `master` into this branch so that the other URL fixes are included?

2022-03-23 10:22 UTC, MikeMcC399 approved these changes
@dsarkar 
Could we get this PR merged in order to correct the issue?

2022-03-23 10:51 UTC, GisoSchroederSAP approved these changes
Seems like a straight-foreward change.
Okay, from my side

2022-03-23 10:53 UTC, dsarkar approved these changes

2022-03-23 10:57 UTC, merged

2022-03-23 10:58 UTC, dsarkar commented
@MikeMcC399 Thanks for rising this issue and reviewing it!