R 2.20 update faq risk update 24
corona-warn-app/cwa-website pull request #2620
Opened 2022-03-29 11:05 UTC by dsarkar

Internal Tracking ID: [EXPOSUREAPP-](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-)

2022-03-29 11:10 UTC, MikeMcC399 commented on src/data/faq.json
> +                                    "Starting with version 2.20, the Corona-Warn-App notifies you when the date of the last encounter with increased risk on the red tile has changed. Previously, you
"..you were not notified again if they had another, ..." =>
"you were not notified again if you had another, "

2022-03-29 11:11 UTC, svengabr approved these changes

2022-03-29 11:11 UTC, MikeMcC399 commented on src/data/faq_de.json
> +                                    "Ab Version 2.20 benachrichtigt die Corona-Warn-App Sie, wenn sich das Datum der letzten Begegnung mit erhöhtem Risiko auf der roten Kachel geändert hat. Zuvor wur
"Zuvor wurden die Sie nicht noch einmal benachrichtigt, wenn sie nach einer Risikobegegnung eine weitere, neuere Begegnung mit erhöhtem Risiko hatten."

=> 

"Zuvor wurden Sie nicht noch einmal benachrichtigt, wenn Sie nach einer Risikobegegnung eine weitere, neuere Begegnung mit erhöhtem Risiko hatten."

2022-03-29 11:12 UTC, MikeMcC399 requested changes
Several typos need to be corrected for the text to make sense.

2022-03-29 11:14 UTC, svengabr commented
Typos fixed, changes approved.

Thanks for review @MikeMcC399 !

2022-03-29 11:37 UTC, merged

2022-04-05 19:47 UTC, Ein-Tim commented
Please delete the branch of this RR. Thanks!