Rework `encounter_19_calc` FAQ entry (Addresses #2120)
corona-warn-app/cwa-website pull request #2622
Opened 2022-03-29 16:24 UTC by Ein-Tim

## Description 

This commit reworks the `encounter_19_calc` FAQ entry.

## What was changed

- https://www.coronawarn.app/en/faq/results/#encounter_19_calc
- https://www.coronawarn.app/de/faq/results/#encounter_19_calc

## Screenshots

| English | German |
|---|---|
| ![Bildschirmfoto 2022-03-29 um 18 22 35](https://user-images.githubusercontent.com/67682506/160659277-8aa5f0ab-fea1-4ac5-a1a2-a010282d96b6.png) | ![Bildschirmfoto 2022-03-29 um 18 21 59](https://user-images.githubusercontent.com/67682506/160659171-8b758287-21a2-45a9-8f8f-2ee659ab09df.png) |

## Contributors 

Thanks to @ahodzic2, who reworked the English FAQ entry.

---

**Closes #2120**

2022-03-29 16:41 UTC, MikeMcC399 requested changes
Suggestion for one anchor link.

2022-03-29 16:42 UTC, Ein-Tim commented on src/data/faq_de.json
> +                                    "Sind diese Kriterien <b>nicht</b> erfüllt, erfolgt <b>keine</b> Zählung innerhalb der App. Es handelt sich um eine „Nicht-Risiko-Begegnung“. Im Kontaktprotokoll d
```suggestion
                                    "Sind diese Kriterien <b>nicht</b> erfüllt, erfolgt <b>keine</b> Zählung innerhalb der App. Es handelt sich um eine „Nicht-Risiko-Begegnung“. Im Kontaktprotokoll des Betriebssystems werden diese Begegnungen zwar gezählt, werden jedoch nicht in die Risikoberechnung der App einbezogen. Siehe dazu den FAQ-Eintrag <a href='/#keys_matches' target='_blank' >Was bedeutet die Überprüfung auf mögliche Begegnungen?</a>.",
```

2022-03-29 16:44 UTC, Ein-Tim commented on src/data/faq_de.json
> +                                    "Sind diese Kriterien <b>nicht</b> erfüllt, erfolgt <b>keine</b> Zählung innerhalb der App. Es handelt sich um eine „Nicht-Risiko-Begegnung“. Im Kontaktprotokoll d
Thanks, you're absolutely right!

Fixed in [`492ea44`](https://github.com/corona-warn-app/cwa-website/pull/2622/commits/492ea4423756eecaae9267cf556636bacfe07411)

2022-03-29 17:06 UTC, MikeMcC399 approved these changes

2022-03-31 08:08 UTC, svengabr approved these changes

2022-03-31 08:31 UTC, merged