FAQ menu hint changed
corona-warn-app/cwa-website pull request #2664
Opened 2022-04-01 13:09 UTC by Crystalskulls

Fix for Issue #2604

Changed the FAQ menu hint for small devices.

2022-04-01 13:14 UTC, Ein-Tim requested changes
This is not an optimal change as the text is also displayed if the menu is already open (e.g. on a desktop browser).

I suggest to find a better solution.

2022-04-01 13:17 UTC, MikeMcC399 commented
I was (again) writing in parallel to @Ein-Tim.

Anyway here is the screenshot. I think it is clear now that it needs some extra logic.

![image](https://user-images.githubusercontent.com/66998419/161270964-d2500e76-1ed8-49c0-a01c-51f957bab5f9.png)

2022-04-01 15:07 UTC, Crystalskulls commented
@Ein-Tim @MikeMcC399 I have committed some additional changes. The hint changes now, while resizing the window.

2022-04-01 15:27 UTC, MikeMcC399 commented
@Crystalskulls 
Excellent! 👍🏻

2022-04-01 15:29 UTC, Ein-Tim approved these changes
Works flawlessly! Thanks!

2022-04-02 09:45 UTC, Crystalskulls commented on src/partials/page-faq-results.html
> +        <div class="filterUse filterUse-sm"><img src="../../../assets/img/icons/info.svg"><span>{{page-contents.section-main.texts.info-filteruse-sm}}</span></div>
That's a good point. I will make an additional change.

2022-04-04 08:25 UTC, larswmh approved these changes

2022-04-04 08:26 UTC, dsarkar approved these changes

2022-04-04 08:39 UTC, merged

2022-04-04 08:42 UTC, dsarkar commented
@Crystalskulls @MikeMcC399 @Ein-Tim Great! Thanks a lot for the PR and reviewing!