Add Rapid PCR Test information to glossary
corona-warn-app/cwa-website pull request #2863
Opened 2022-05-10 07:01 UTC by larswmh

New:
- #glossary_rapid_pcr_test:
![chrome_h0xeE6eKax](https://user-images.githubusercontent.com/88365935/167567013-1ecba784-1bd8-425f-a96a-1cc8216933a3.png) ![chrome_vxrA2qV0MU](https://user-images.githubusercontent.com/88365935/167567019-8a575bc5-677e-445c-aed3-7e299beeab41.png)

Updated:
- #glossary_pcr_test: 
![chrome_RZtuxLBJJ0](https://user-images.githubusercontent.com/88365935/167567018-e829899c-db8f-44f2-9e87-68330e8e0e70.png) ![chrome_IMt56xuRGf](https://user-images.githubusercontent.com/88365935/167567024-aa04e59d-d6b0-40e6-98d9-25a39e514876.png)
- #glossary_rapid_test: 
![chrome_pYRdu0zDMI](https://user-images.githubusercontent.com/88365935/167567021-852b6706-2c76-4922-ae4d-9cde3e075c0a.png) ![chrome_sUAlmD6arw](https://user-images.githubusercontent.com/88365935/167567023-48ec5bb0-abc1-4be1-a093-9eac4b8d4685.png)

---
Internal Tracking ID: [EXPOSUREAPP-12476](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12476)

2022-05-10 07:20 UTC, MikeMcC399 commented on src/data/faq.json
> +                    "description": "Rapid PCR tests, or also often referred to as \"PoC-NAT-tests\", are based on the same technology as regular PCR tests, but can be evaluated quickly and on-site an
"or also often referred to as" => "also often referred to as"

"precautions" => "preparations"

(https://dictionary.cambridge.org/dictionary/english/precaution "an action  that is done to prevent something unpleasant or dangerous happening". A Rapid PCR Test is not a dangerous event!)

2022-05-10 07:21 UTC, MikeMcC399 requested changes
Suggestions for English text added in-line.

2022-05-10 07:22 UTC, MikeMcC399 commented
- This PR resolves https://github.com/corona-warn-app/cwa-website/issues/2586.

2022-05-10 07:30 UTC, larswmh commented on src/data/faq.json
> +                    "description": "Rapid PCR tests, or also often referred to as \"PoC-NAT-tests\", are based on the same technology as regular PCR tests, but can be evaluated quickly and on-site an
Thanks for your suggestions! They have been applied in https://github.com/corona-warn-app/cwa-website/pull/2863/commits/c7b30a852d06877048d36c9f336db2d6f70b9d34

2022-05-11 11:58 UTC, GisoSchroederSAP reviewed
I added two comments. Other than that, fine, go ahead and do the changes.

2022-05-11 11:58 UTC, GisoSchroederSAP commented on src/data/faq.json
> +                    "description": "Rapid PCR tests, also often referred to as \"PoC-NAT-tests\", are based on the same technology as regular <a href='#glossary_pcr_test'>PCR tests</a>, but can be ev
in English, I think the right term is "PoC-NAAT"; the double 'A' comes fro mthe long name "Nucleic **A**cid **A**mplification Test", so the trainling "test" would not be required either - but makes it more readable

2022-05-11 11:58 UTC, GisoSchroederSAP commented on src/data/faq_de.json
> +                    "description": "PCR-Schnelltests, die oft auch als \"PoC-NAT-Tests\" bezeichnet werden, basieren auf der selben Technik wie reguläre <a href='#glossary_pcr_test'>PCR Tests</a>, la
Please use "derselben" as a single instead of "der selben"

2022-05-11 12:05 UTC, larswmh commented on src/data/faq.json
> +                    "description": "Rapid PCR tests, also often referred to as \"PoC-NAT-tests\", are based on the same technology as regular <a href='#glossary_pcr_test'>PCR tests</a>, but can be ev
Thanks for poining that out. It has been changed in https://github.com/corona-warn-app/cwa-website/pull/2863/commits/8bfbbbe1adecd24b3108f26cffde3cea25d6459f

2022-05-11 12:05 UTC, larswmh commented on src/data/faq_de.json
> +                    "description": "PCR-Schnelltests, die oft auch als \"PoC-NAT-Tests\" bezeichnet werden, basieren auf der selben Technik wie reguläre <a href='#glossary_pcr_test'>PCR Tests</a>, la
Thanks for pointing that out. It has been changed in https://github.com/corona-warn-app/cwa-website/pull/2863/commits/8bfbbbe1adecd24b3108f26cffde3cea25d6459f

2022-05-11 12:11 UTC, dsarkar approved these changes

2022-05-11 12:13 UTC, merged