Release 2.24
corona-warn-app/cwa-website pull request #2959
Opened 2022-06-15 05:38 UTC by larswmh

2022-06-28 11:59 UTC, MikeMcC399 commented
Manually executing `npm test` passes on this branch 👍🏻

2022-06-28 13:46 UTC, MikeMcC399 commented on src/data/faq.json
> +                                    "<b>Updated ??? ?? ????</b><hr>",
This line needs to be updated before merging.

2022-06-28 13:48 UTC, MikeMcC399 requested changes
Perhaps this PR should be in draft status or https://github.com/corona-warn-app/cwa-website/labels/do-not-merge until it is ready?

2022-06-28 13:50 UTC, larswmh commented
Any that is missing by now, such as the release date, will be added shortly before merging

2022-06-29 06:43 UTC, MikeMcC399 commented
http://localhost:8000/assets/screenshots/2-24/en/android/VaccinationDetailsFragment_immune_2.png is incorrect.

![image](https://user-images.githubusercontent.com/66998419/176369021-b6e66c5c-138c-479d-bf7d-20b7f48015e1.png)

The text "Please make sure to get a new digital certificate in time." has been removed from the app.

- See https://github.com/corona-warn-app/cwa-app-android/pull/5282

2022-06-29 10:26 UTC, MikeMcC399 commented
@larswmh 

Where the text  "Please make sure to get a new digital certificate in time."  is removed in 2.24, it does not leave a blank space, instead the text "Technical Expiration Date<br>Valid until mm/dd/yy, hh:mm AM" becomes visible.

![image](https://user-images.githubusercontent.com/66998419/176414661-08c3adb8-bb48-4dff-b014-3493e807787e.png)

2022-06-29 10:39 UTC, larswmh commented
@MikeMcC399 

> Where the text "Please make sure to get a new digital certificate in time." is removed in 2.24, it does not leave a blank space, instead the text "Technical Expiration Date
Valid until mm/dd/yy, hh:mm AM" becomes visible.

Thanks for your comment. In addition to fixing this, I have replaced both VaccinationDetailsFragment, which were incorrectly invalid, with a valid version.

2022-06-29 16:02 UTC, merged

2022-06-29 16:32 UTC, MikeMcC399 commented
@larswmh 

The blog has been published under the link
- https://www.coronawarn.app/en/blog/2022-06-29-cwa-2-24/ and
- https://www.coronawarn.app/de/blog/2022-06-29-cwa-2-24/

however the FAQ article (EN)
- https://www.coronawarn.app/en/faq/results/#eu_dcc_export and
links to the non-existent 
https://www.coronawarn.app/en/blog/2022-06-29-cwa-version-2-24/

and the FAQ article (DE)
- https://www.coronawarn.app/de/faq/results/#eu_dcc_export and
links to the non-existent 
https://www.coronawarn.app/de/blog/2022-06-29-cwa-version-2-24/

The links to the blog need to be corrected. Will you do this?