Update FAQ: Mention end date of free test entitlement
corona-warn-app/cwa-website pull request #2984
Opened 2022-06-27 14:18 UTC by larswmh

Fixes #2962 

[#voluntary_self_quarantine](https://www.coronawarn.app/en/faq/results/#voluntary_self_quarantine)
![image](https://user-images.githubusercontent.com/88365935/175962514-ce620f5d-5c6c-4b0c-9708-c1dc73f84bf4.png)
![image](https://user-images.githubusercontent.com/88365935/175962523-0fdcc57c-f212-476b-886f-964d3bd215f8.png)

[#vac_cert_red_warning](https://www.coronawarn.app/en/faq/results/#vac_cert_red_warning)
![image](https://user-images.githubusercontent.com/88365935/175962543-61856047-05f2-4369-aec2-134b078f11d7.png)
![image](https://user-images.githubusercontent.com/88365935/175962548-0442531f-1b49-4ccb-87e3-116ddc878d9e.png)

Internal Tracking ID: [EXPOSUREAPP-13400](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13400)

2022-06-27 17:15 UTC, MikeMcC399 commented on src/data/faq_de.json
> +                                    "Sollte die Corona-Warn-App Ihnen eine Begegnung mit erhöhtem Risiko in einer roten Kachel anzeigen, begeben Sie sich, wenn möglich, in eine freiwillige Selbstquar
Wrong month. It should be Juni, not Juli.

2022-06-27 17:20 UTC, MikeMcC399 commented
This PR successfully covers the period up until June 30, 2022. Further changes will be necessary after this date.

See https://www.bundesgesundheitsministerium.de/coronavirus.html#c23063:

**_Lauterbach: „Bürgertests werden aussagekräftiger und zielgenauer“_**

_Auch mit dem Inkrafttreten der neuen Testverordnung am 30. Juni wird es eine flächendeckende Infrastruktur für Bürgertests geben. Vulnerable Gruppen werden weiterhin kostenlose Tests erhalten. Im Normalfall müssen sich Bürger und Bürgerinnen aber mit 3 Euro an einem Test beteiligen. Kontrollfrequenz und -qualität in den Testzentren sollen verbessert werden. „Es geht darum die Testzentren zu erhalten, Infektionsketten zu unterbrechen - indem die Tests dort eingesetzt werden, wo sie den größten Nutzen haben - und Betrug und Missbrauch zu reduzieren“, so Bundesgesundheitsminister Prof. Lauterbach. ..._

2022-06-27 17:20 UTC, MikeMcC399 requested changes
In one place the wrong month is used. It should be June everywhere.

2022-06-28 11:19 UTC, larswmh commented
Thanks for your review @MikeMcC399. As the problem with the wrong month has now been solved, I think this PR is ready to be merged.

2022-06-28 11:19 UTC, merged