Update privacy statement: Change president
corona-warn-app/cwa-website pull request #3440
Opened 2023-03-24 15:34 UTC by larswmh

This PR changes the president mentioned in the privacy statement.

![image](https://user-images.githubusercontent.com/88365935/227570857-b6c5c1e8-26eb-4fa9-8315-5f3b53a80ca2.png)
![image](https://user-images.githubusercontent.com/88365935/227570862-46cb6bcf-dd0c-4c69-9689-85cce0d43e25.png)

---
Internal Tracking ID: [EXPOSUREAPP-14634](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14634)

2023-03-24 15:51 UTC, MikeMcC399 commented on src/data/privacy_de.json
> +                "Robert Koch-Institut (RKI)<br />Nordufer 20<br />13353 Berlin<br />vertreten durch den Präsidenten i.V. Prof. Dr. Schaade",
written out this means:

"vertreten durch den Präsidenten in Vertretung Prof. Dr. Schaade"

which sounds a bit strange!

Does this mean that Prof. Dr. Schaade is not the real President and he is only standing in for him?

2023-03-27 10:23 UTC, MikeMcC399 commented on src/data/privacy_de.json
> +                "Robert Koch-Institut (RKI)<br />Nordufer 20<br />13353 Berlin<br />vertreten durch den Präsidenten i.V. Prof. Dr. Schaade",
@larswmh 

Yes, thanks for asking. I have hidden my comment now as "resolved".

2023-03-31 13:01 UTC, dsarkar approved these changes

2023-03-31 13:38 UTC, Ein-Tim requested changes
This is not approved. You'll receive a mail from me shortly!

2023-03-31 13:44 UTC, brianebeling approved these changes

2023-03-31 13:44 UTC, Ein-Tim commented
Mail's out, latest info I got was to use "vertreten durch den Präsidenten" bzw. "vertreten durch den komm. Präsidenten", as it is used in the Impressum of rki.de

2023-03-31 13:50 UTC, dsarkar commented
changes approved.

2023-03-31 13:51 UTC, dsarkar commented
@Ein-Tim Many thanks!

2023-03-31 13:51 UTC, larswmh commented
We changed it to "Vertreten durch den Präsidenten" / "Represented by the President", which is exactly how it is used on the RKI website

2023-03-31 13:52 UTC, Ein-Tim approved these changes
Looks good to me now, thanks!

2023-03-31 13:55 UTC, merged