FAQ - New exposure check intervals (< 24h)
corona-warn-app/cwa-website pull request #632
Opened 2020-11-29 18:40 UTC by heinezen

Resolves https://github.com/corona-warn-app/cwa-website/issues/628

2020-11-29 20:52 UTC, MikeMcC399 commented
https://www.coronawarn.app/en/faq/#multiple_exposure_checks says;

"When the app downloads the current diagnosis keys from the server, a check of the exposure log is performed. During that process, a separate check is performed for each of the last 14 days, for which diagnosis keys are available. It is therefore not an error that multiple, seemingly simultaneous entries are visible in the exposure check history. You can further click on the details of each check to see that different amounts of keys were provided for each of them."

There are no longer "multiple, seemingly simultaneous entries visible in the exposure check history" and this is not expected when CWA has been updated to the current version of the app >= 1.6.x.

Starting with CWA 1.7.x the app checks a minimum of once a day when the device only has connectivity to a mobile data network **and** every 4 hours (in other words 6 times a day) with WiFi connectivity. It does **not** cause 14 entries with more or less the same timestamp in the exposure log any more.

Could we get the entry https://www.coronawarn.app/en/faq/#multiple_exposure_checks in the FAQs also updated accordingly?

2020-11-30 13:32 UTC, loki-cui requested changes
typo in german translation -> last word = "abgefragr" instead of "abgefragt"

2020-11-30 21:20 UTC, MikeMcC399 requested changes
Bitte Schreibfehler korrigieren!

2020-11-30 21:20 UTC, MikeMcC399 commented on src/data/faq_de.json
> +                            "Seit Version 1.7 der Corona-Warn-App wird der Risikostatus bis zu 6 mal täglich aktualisiert, wenn eine WLAN-Verbindung vorhanden ist. Die wiederholte Abfrage wird automa
mobiilen => mobilen

2020-12-01 09:39 UTC, MikeMcC399 commented
Please also update the current app version numbers on the main page https://www.coronawarn.app/en/, where it still says:

"1. Download the current version of the app (iOS: 1.6.1 or Android: 1.6.1)"

whereas the changed files in this PR already reference version 1.7.

2020-12-01 10:14 UTC, dsarkar commented
@MikeMcC399, @loki-cui 

corrected-->

mobile
abgefragt.

2020-12-01 10:15 UTC, dsarkar approved these changes

2020-12-01 10:26 UTC, loki-cui approved these changes

2020-12-01 10:38 UTC, merged