FAQ - Change exposure log paths and remove deprecated info
corona-warn-app/cwa-website pull request #645
Opened 2020-12-06 17:48 UTC by heinezen

Fixes #618 

Incorporates additional info for background updates since v1.7.0

2020-12-07 07:27 UTC, MikeMcC399 commented on src/data/faq.json
> +                            "<ol><li>The log has a fixed limit of 100 entries on iOS devices. If there are more entries, only the latest are kept. We're in contact with Apple so that the complete log
Suggest changing:

The log limit of 100 entries on Android devices has been recently removed by Google at the end of August 2020.

to:

Android devices are limited to 300 entries.

2020-12-07 07:29 UTC, MikeMcC399 commented on src/data/faq_de.json
> +                            "<ol><li>Diese Übersicht hat ein festes Limit von 100 Einträgen auf iOS Geräten. Wird dieses Limit überschritten, werden nur die neuesten Einträge behalten. Sie sehen dann
Suggest changing:

Die Protokollgrenze von 100 Einträgen auf Android-Geräten wurde kürzlich von Google Ende August 2020 entfernt.

to

Android-Geräten haben eine Protokollgrenze von 300 Einträge.

2020-12-07 07:32 UTC, MikeMcC399 requested changes
The current text implies that the limit of 100 was removed and there is now no limit. Android devices are limited to 300 entries. The log is not allowed to increase without limit.

See my note in https://github.com/corona-warn-app/cwa-app-android/issues/1020#issuecomment-722373534 and the exposure log linked to https://github.com/corona-warn-app/cwa-app-android/issues/1817#issuecomment-739553078

Also the text mentioning August 2020 as being recent is no longer up-to-date. You could possibly say that the limit was increased from 100 to 300 in August, but that is a historical fact that is hardly relevant today. The important point is the current limit of 300.

2020-12-08 12:37 UTC, heinezen commented
@MikeMcC399 Thanks!

I've updated the answer again. Only used a slightly different phrasing and completely removed the mentioning of August 2020.

2020-12-08 13:09 UTC, MikeMcC399 commented
@heinezen 
> I've updated the answer again. Only used a slightly different phrasing and completely removed the mentioning of August 2020.

The limit of 300 for Android is sufficient for normal use. (14 days x 6 times per day = 84 entries, which gives a reserve of 216 entries.) I don't know a reason why you would want to ask Google to increase the limit above 300. There is a danger of filling up device memory if there is a problem. We've seen some error situations where the limit of 300 is hit because the aging out of entries older than 14 days is not working.

For iOS the statement that you are in contact with Apple has been there a long time. It doesn't sound like anything is going to get resolved. I'm not involved with iOS so I don't have any further insight there.

2020-12-10 14:09 UTC, heinezen commented
@MikeMcC399 The last information I found on this is that we are still trying to get all OSs to display the full logs for error reporting. For iOS, this might be resolved in a later ENA version.

I've removed the sentence now, since the log shouldn't fill up under normal circumstances.

----
Corona-Warn-App Open Source Team

2020-12-10 14:32 UTC, MikeMcC399 requested changes
Thank you for removing the comment about trying to get the limit reduced.

I noticed one other point in the German text "Sie sehen dann typischerweise die Einträge von 7 Tagen." which is not true for Android and the equivalent statement isn't present in the English text. Please consider removing this statement.

2020-12-10 14:32 UTC, MikeMcC399 commented on src/data/faq_de.json
> +                            "<ol><li>Diese Übersicht hat ein festes Limit von 100 Einträgen auf iOS Geräten. Auf Android-Geräten beträgt das Limit 300 Einträge. Wird dieses Limit überschritten, werde
"Diese Übersicht hat ein festes Limit von 100 Einträgen auf iOS Geräten. Auf Android-Geräten beträgt das Limit 300 Einträge. Wird dieses Limit überschritten, werden nur die neuesten Einträge behalten. **Sie sehen dann typischerweise die Einträge von 7 Tagen.**"

On Android it is not expected that the limit would be reached and typically you see entries for 16 days. I would just remove the sentence "Sie sehen dann typischerweise die Einträge von 7 Tagen."

2020-12-11 11:17 UTC, dsarkar commented
![image](https://user-images.githubusercontent.com/1409741/101897189-73e81200-3baa-11eb-9674-fdec0e44ccab.png)

![image](https://user-images.githubusercontent.com/1409741/101897235-86624b80-3baa-11eb-9297-f2ea3ef56e1d.png)


@MikeMcC399 @loki-cui - Please review. Thanks

2020-12-11 11:19 UTC, dsarkar approved these changes

2020-12-11 11:24 UTC, dsarkar approved these changes

2020-12-11 11:25 UTC, loki-cui approved these changes

2020-12-11 11:27 UTC, dsarkar approved these changes

2020-12-11 11:28 UTC, merged

2020-12-11 11:41 UTC, MikeMcC399 commented
@dsarkar 
LGTM. Thank you!