FAQ - New risk assessment category
corona-warn-app/cwa-website pull request #646
Opened 2020-12-08 13:45 UTC by heinezen

Resolves https://github.com/corona-warn-app/cwa-website/issues/637

2020-12-08 14:00 UTC, dsarkar commented
EN Output

![image](https://user-images.githubusercontent.com/1409741/101492980-ba98fa80-3965-11eb-91ca-209bcdc378c7.png)
![image](https://user-images.githubusercontent.com/1409741/101493080-db615000-3965-11eb-8756-0cbb5f924af8.png)
![image](https://user-images.githubusercontent.com/1409741/101493117-e7e5a880-3965-11eb-976b-b6ca609ab001.png)

2020-12-08 14:01 UTC, dsarkar commented
DE Output

![image](https://user-images.githubusercontent.com/1409741/101493239-18c5dd80-3966-11eb-9d3a-d1e27089d2da.png)
![image](https://user-images.githubusercontent.com/1409741/101493271-2713f980-3966-11eb-8119-a76566ea3117.png)
![image](https://user-images.githubusercontent.com/1409741/101493295-3004cb00-3966-11eb-8579-e4338a435b76.png)

2020-12-08 14:58 UTC, MikeMcC399 commented on src/data/faq_de.json
> +                "title": "Risko-Ermittlung",
Typo
"title": "Risko-Ermittlung", => "title": "Risiko-Ermittlung",

2020-12-08 15:03 UTC, MikeMcC399 commented on src/data/faq_de.json
> +                            "Nein, denn auf Grundlage der Daten der Risiko-Ermittlung wird das Infektionsrisiko als niedrig eingestuft, da sich die Begegnung auf einen kurzen Zeitraum und/oder einen
Typo:
Die Verhaltensvorschläge sowie Infos zum Ermittlungszeitraum als auch zum Infektionsrisiko finden Nutzer*innen in der App selbst, wenn sie auf „Niedriges **Risik**“ mit dem Finger tippen.

Risik => Risiko

2020-12-08 15:07 UTC, MikeMcC399 requested changes
There are two typos in the German section that should be corrected: both concerning the word "Risiko" for some reason!

2020-12-09 09:43 UTC, loki-cui requested changes
As pointed out by MikeMcC399, pls. correct the typo.

2020-12-09 10:21 UTC, dsarkar approved these changes

2020-12-09 10:23 UTC, dsarkar commented
Thanks. Typo 2x "Risiko" corrected now.

2020-12-09 10:23 UTC, dsarkar commented on src/data/faq_de.json
> +                "title": "Risko-Ermittlung",
ok

2020-12-09 10:24 UTC, dsarkar approved these changes

2020-12-09 10:28 UTC, loki-cui approved these changes

2020-12-09 11:02 UTC, merged