Include workaround reg. switching to new devide
corona-warn-app/cwa-website pull request #648
Opened 2020-12-08 18:01 UTC by Ein-Tim

Closes #411 

---

I included the text I proposed [here](https://github.com/corona-warn-app/cwa-website/issues/411#issuecomment-740747515) in the FAQ entry(s):

- https://www.coronawarn.app/de/faq/#backup
- https://www.coronawarn.app/en/faq/#backup

I hope I handled the Links okay, if not lemme now or feel free to change something (edit by maintainers is allowed)

Sorry for the typo in the commit 😀

2020-12-09 07:39 UTC, MikeMcC399 commented on src/data/faq_de.json
> +                            "Falls Sie zu einem neuem Handy gewechselt haben und über alle Kontakte informiert werden wollen ist es notwendig, dass sie auf ihrem alten Gerät die Corona-Warn App noch
"dass sie auf ihrem alten Gerät" => "dass Sie auf Ihrem alten Gerät"

2020-12-09 07:41 UTC, MikeMcC399 commented on src/data/faq_de.json
> +                            "Eine Anleitung, wie sie Ihr Testergebnis auf mehreren Geräten teilen könnn, finden Sie <a href='#test_multiple_devices' target='_blank' rel='noopener'>Wie teile ich ein p
"wie sie Ihr Testergebnis auf mehreren Geräten teilen könnn" => "wie Sie Ihr Testergebnis auf mehreren Geräten teilen können"

2020-12-09 07:47 UTC, MikeMcC399 requested changes
There are several typos in the German text to be corrected.
You can also correct the typo in the PR title "devide" => "device" which you should be able to edit independently from the original commit text.

Did you test using npm according to the https://github.com/corona-warn-app/cwa-website/blob/master/README.md instructions?

If you do that it is already really helpful to have a screen shot of the new web page pasted into the PR to review, since it is quite hard to look at the long lines of text in the .json files.

2020-12-09 15:18 UTC, Ein-Tim commented
@MikeMcC399 
I will mark this PR as WIP since I'm a bit bussy at the moment... Will come back to you at the weekend (I will also share the screenshots at the weekend).

I also thought that I would maybe would be better to have a seperate FAQ Entry regarding this...
@dsarkar Could you give your opinion regarding this? 

Thanks!

2020-12-10 07:40 UTC, dsarkar commented
@Ein-Tim, @MikeMcC399, we will have a look at this. Looks good so far. Will come back to you. DS

2020-12-10 08:00 UTC, dsarkar commented
![image](https://user-images.githubusercontent.com/1409741/101738170-0bc00000-3ac6-11eb-89cd-199b0f8a585f.png)
![image](https://user-images.githubusercontent.com/1409741/101738231-1da1a300-3ac6-11eb-826d-fd6f2ed2fca6.png)

2020-12-10 08:10 UTC, Ein-Tim commented
Mark to myself:
Include `all contacts` in the English text 😀

2020-12-10 15:13 UTC, Ein-Tim commented
Since @heinezen already [started to draft](https://github.com/corona-warn-app/cwa-website/issues/411#issuecomment-742561389) an own FAQ Entry about this, I will close this PR.

2020-12-10 15:29 UTC, MikeMcC399 commented
@Ein-Tim 
Perhaps leave this in draft mode and then modify it later to refer to the main FAQ article about migrating to a new device? It would still have some value to refer to what to do in a backup article.

2020-12-11 08:58 UTC, loki-cui approved these changes

2020-12-11 21:17 UTC, Ein-Tim commented
Since #653 was merged, the changes I made until now are obsolete. @MikeMcC399, I'm waiting for your proposal 😀
Thanks for the good cooperation!

2020-12-12 09:35 UTC, MikeMcC399 commented
@Ein-Tim 
The FAQ article https://www.coronawarn.app/en/faq/#new_device is directly below the article https://www.coronawarn.app/en/faq/#backup, so there is a high probability that a reader of the backup article will see the one about a new device as well. Also if a user searches for the term "backup" it will bring up both articles.

In that case I would suggest not making any changes to the backup article (like a cross-reference to the adjacent new device article). 

Readers have the relevant information available to them without any further changes.

Thanks once again for your active involvement. 👍 

![image](https://user-images.githubusercontent.com/66998419/101980451-a7d43d80-3c65-11eb-872e-9e88478ca5e3.png)

2020-12-12 09:36 UTC, Ein-Tim commented
Okay, thanks for the feedback. Closing this now 👍

2020-12-12 09:36 UTC, closed without merging