FAQ - Better QR code entries
corona-warn-app/cwa-website pull request #663
Opened 2020-12-13 18:15 UTC by heinezen

Fixes https://github.com/corona-warn-app/cwa-website/issues/549

What has been done:
* Split the entry into two: One for scanning, one for a delayed test result
* Restructure the `qr_scan` entry for better readability
* Remove notice about entering the code twice, Should be covered by https://www.coronawarn.app/de/faq/#test_multiple_devices

2020-12-13 18:59 UTC, MikeMcC399 requested changes
There is a basic mistake in the section
"I get an error while scanning the QR code. What can I do?"
referring to the reason 
"The test result was not allowed to be transmitted."

That is not the way it works.

As @thomasaugsten noted in https://github.com/corona-warn-app/cwa-app-android/issues/1551#issuecomment-723227499 a user should normally be able to scan in a correct QR code. This is independent of whether the consent field on the form is marked, or if the lab has entered the code into the lab system. 

The reasons it might not work are:
- defective QR code on printed form
- the code has already been used
and the reasons for this include:
- the form has been copied and re-used for multiple tests
- the QR code has already been scanned in by the user themselves and then deleted

The error message `submission_qr_code_scan_invalid_dialog_body` does not distinguish between the different error causes.

<string name="submission_qr_code_scan_invalid_dialog_headline">"**QR code is invalid**"</string>
<string name="submission_qr_code_scan_invalid_dialog_body">"The QR code is invalid or has been registered on another smartphone already. You will receive your test result from the test center or laboratory regardless of the validity of the QR code. If you are diagnosed with COVID-19, the public health authority will be notified through the legally prescribed channel and will contact you."</string>
   

So this reason (missing consent and missing lab input) needs to be moved into the section
"I have scanned a QR code, but the test result could not be retrieved for days."

2020-12-15 11:51 UTC, heinezen commented
New revised entry is here.

2020-12-15 13:01 UTC, MikeMcC399 requested changes
Syntax error.

If you could correct this, it will be easier to review using the local webserver.

2020-12-15 13:01 UTC, MikeMcC399 commented on src/data/faq.json
> +                            "Please check whether the laboratory with which the doctor or the test center works is connected to the Corona-Warn-App and whether field 9 is checked on the form. Only th
comma is missing at end of line, leading to a syntax error.

"Please check whether the laboratory with which the doctor or the test center works is connected to the Corona-Warn-App and whether field 9 is checked on the form. Only then is it ensured that the procedure used works with the Corona-Warn-App."

2020-12-15 13:07 UTC, MikeMcC399 commented on src/data/faq.json
> +                            "If you have scanned your QR code into the App after a corona test and do not receive a test result via the App within a few days, it is possible that the respective labor
Capitalise corona -> Corona

2020-12-15 13:09 UTC, MikeMcC399 commented on src/data/faq_de.json
> +                            "Jeder QR Code den sie erhalten kann nur einmal in der App eingegeben werden. Falls Sie die Corona-Warn-App auf mehreren Geräten verwenden, können Sie den QR Code nur in e
erhalten kann -> erhalten, kann  (missing comma)

2020-12-15 13:17 UTC, MikeMcC399 commented
There is new information in https://github.com/corona-warn-app/cwa-app-android/issues/1551#issuecomment-745266898 from @dsarkar who wrote:

> It is now possible to scan the QR code twice

Does that mean a QR code can be scanned once or twice, but not three or more times?

This needs some clarification.

2020-12-15 13:59 UTC, heinezen commented
@MikeMcC399 I fixed the minor errors.

Regarding scanning the QR code twice: This should be a recent change. I'll have to check how this manifests itself when using the app.

----
Corona-Warn-App Open Source Team

2020-12-15 15:25 UTC, MikeMcC399 commented on src/data/faq.json
> +                            "<ul><li>'Inform & Help' -> 'Continue' -> 'TAN'</li></ul>"
` "<ul><li>'Inform & Help' -> 'Continue' -> 'TAN'</li></ul>"` does not correspond to UI
Change to
` "<ul><li>'LEARN MORE AND HELP' -> 'NEXT' -> 'TAN'</li></ul>"`

---
![LEARN MORE AND HELP](https://user-images.githubusercontent.com/66998419/102234781-ec740900-3ef1-11eb-8c03-58789d6ef30b.jpg)

---
![NEXT](https://user-images.githubusercontent.com/66998419/102234842-fd247f00-3ef1-11eb-8857-f004efe30af1.jpg)

---
![TAN_en](https://user-images.githubusercontent.com/66998419/102234873-03b2f680-3ef2-11eb-93d4-fd4413437a4c.jpg)

2020-12-15 15:28 UTC, MikeMcC399 commented on src/data/faq_de.json
> +                            "<ul><li>'Informieren & Helfen' -> 'Weiter' -> 'TAN'</li></ul>",
`"<ul><li>'Informieren & Helfen' -> 'Weiter' -> 'TAN'</li></ul>",`
capitalise to correspond to appearance in UI
`"<ul><li>'INFORMIEREN & HELFEN' -> 'WEITER' -> 'TAN'</li></ul>",`

---
![INFORMIEREN   HELFEN](https://user-images.githubusercontent.com/66998419/102235253-6e643200-3ef2-11eb-91b0-583ef0772aa3.jpg)

---
![WEITER](https://user-images.githubusercontent.com/66998419/102235278-7623d680-3ef2-11eb-801a-327f6789147c.jpg)

---
![TAN_de](https://user-images.githubusercontent.com/66998419/102235293-7a4ff400-3ef2-11eb-963a-b07d3efc67fd.jpg)

2020-12-15 15:31 UTC, MikeMcC399 requested changes
The instructions for submitting a TAN through the English UI are not correct, so I suggested corrections together with screen shots for verification.

For consistency I also suggested capitalising the words for the German UI so that they are exactly the same as they appear on the user's screen.

2020-12-15 15:37 UTC, MikeMcC399 commented
@heinezen 
> Regarding scanning the QR code twice: This should be a recent change. I'll have to check how this manifests itself when using the app.

You can disregard this point, as it was a typo from @dsarkar !  
I couldn't imagine how this would work and he confirmed the mistake in https://github.com/corona-warn-app/cwa-app-android/issues/1551#issuecomment-745356579.

2020-12-16 19:01 UTC, MikeMcC399 commented
According to https://www.coronawarn.app/en/blog/2020-12-16-corona-warn-app-version-1-9/ CWA 1.9 is being released to all devices over the next 48 hours, and the screen shots there are different.

To enter a TAN:
- English:
NEXT STEPS > Enter TAN

- German;
NÄCHSTE SCHRITTE > TAN-Eingabe

I can only test with the release/1.9.x debug version at the moment. I don't have access to any released 1.9.x version on Android.

2020-12-17 14:07 UTC, heinezen commented
@MikeMcC399 I finally got the texts from the new release. They went trough several iterations.

The font should noot be apitalized anymore in 1.9

2020-12-17 15:42 UTC, MikeMcC399 commented
@heinezen  
> The font should noot be apitalized anymore in 1.9

Did you check to see how the text is displayed on a device? I am seeing the text "NEXT STEPS" / "NÄCHSTE SCHRITTE" displayed in capital letters.

Also, in the app version I'm running 1.9.1-RC1, cloned from the "main" branch, the step 'Next' / 'Weiter' is no longer shown - so one step less than in the version 1.7.1.

2020-12-17 16:51 UTC, heinezen commented
@MikeMcC399 I'll wait for the Android release then, because I presume the mockups I looked at are outdated. Development is too rapid in this case 🔧 :D 

The Android release should be completely rolled out in the next days

2020-12-19 11:59 UTC, MikeMcC399 commented on src/data/faq.json
> +                            "<ul><li>'Next Steps' -> 'Next' -> 'Enter TAN'</li></ul>"
Change `"<ul><li>'Next Steps' -> 'Next' -> 'Enter TAN'</li></ul>"` to
`"<ul><li>'NEXT STEPS' -> 'Enter TAN'</li></ul>"`

Screenshots from released CWA Android 1.9.1
---
![En_have_you_been_tested](https://user-images.githubusercontent.com/66998419/102688833-bab4b800-41f9-11eb-9a4a-fa8693f27f26.jpg)

---
![En_did_you_test_positive](https://user-images.githubusercontent.com/66998419/102688840-c902d400-41f9-11eb-8483-f301e53fda75.jpg)

2020-12-19 12:05 UTC, MikeMcC399 commented on src/data/faq_de.json
> +                            "<ul><li>'Nächste Schritte' -> 'Weiter' -> 'TAN-Eingabe'</li></ul>",
Change `"<ul><li>'Nächste Schritte' -> 'Weiter' -> 'TAN-Eingabe'</li></ul>",` to
`"<ul><li>'NÄCHSTE SCHRITTE' -> 'TAN-Eingabe'</li></ul>",`

Screenshots from released CWA Android 1.9.1
---
![De_wurden_Sie_gestestet](https://user-images.githubusercontent.com/66998419/102688933-aa510d00-41fa-11eb-9b17-ce09e917af7a.jpg)

---
![De_Ihr_Test_ist_positiv](https://user-images.githubusercontent.com/66998419/102688937-b046ee00-41fa-11eb-8c06-9ad20f554397.jpg)

2020-12-19 12:06 UTC, MikeMcC399 requested changes
Comments are updated with screen shots from the released version of CWA Android 1.9.1 obtained from the Google Play Store.

2020-12-20 16:16 UTC, heinezen commented
Updated to use capitalization.

2020-12-20 16:52 UTC, merged

2020-12-20 16:53 UTC, heinezen commented
And merged