Updated Enf 2 risk calculation blog post
corona-warn-app/cwa-website pull request #697
Opened 2020-12-17 15:09 UTC by HannaHei

2020-12-17 15:11 UTC, Ein-Tim requested changes
One german sentence does not make sense

2020-12-17 15:11 UTC, Ein-Tim commented on blog/2020-12-17-risk-calculation-enf-2-0/index_de.md
> +- Es stehen die aktualisierten Diagramme auf Github: https://github.com/corona-warn-app/cwa-documentation/tree/master/images/risk_calculation
```suggestion
- Es stehen aktualisierten Diagramme auf Github zur Verfügung: https://github.com/corona-warn-app/cwa-documentation/tree/master/images/risk_calculation
```

2020-12-17 15:23 UTC, Ein-Tim commented on blog/2020-12-17-risk-calculation-enf-2-0/index_de.md
> +- Es stehen die aktualisierten Diagramme auf Github: https://github.com/corona-warn-app/cwa-documentation/tree/master/images/risk_calculation
Resolved with: #700

2020-12-20 20:37 UTC, dsarkar commented
Hi @HannaHei, this PR can be closed, correct? The blog is online already.

2020-12-21 07:56 UTC, closed without merging

2020-12-21 07:57 UTC, HannaHei commented
Done