FAQ ENA.ExposureNotificationError-Error2
corona-warn-app/cwa-website pull request #746
Opened 2020-12-31 11:07 UTC by dsarkar

closes https://github.com/corona-warn-app/cwa-website/issues/743

2020-12-31 11:17 UTC, dsarkar commented
EN
![image](https://user-images.githubusercontent.com/1409741/103408246-f2a8ed00-4b61-11eb-8890-6ebd9303beee.png)

DE
![image](https://user-images.githubusercontent.com/1409741/103408286-166c3300-4b62-11eb-9409-ff793d1031aa.png)

2020-12-31 11:28 UTC, MikeMcC399 commented on src/data/faq.json
>                              "Afterwards the permissions in the Corona-Warn App have to be assigned again. You will be prompted to do so when the App is started."
Corona-Warn App => Corona-Warn-App

2020-12-31 11:28 UTC, MikeMcC399 commented on src/data/faq_de.json
>                              "Im Anschluss müssen die Berechtigungen in der Corona-Warn App erneut vergeben werden. Dazu werden Sie beim Start der App aufgefordert."
Corona-Warn App => Corona-Warn-App

2020-12-31 11:29 UTC, MikeMcC399 requested changes
I suggest changing Corona-Warn App to Corona-Warn-App (add hyphen) to be consistent with how it is written in other FAQ entries.

2020-12-31 12:43 UTC, dsarkar commented on src/data/faq_de.json
>                              "Im Anschluss müssen die Berechtigungen in der Corona-Warn App erneut vergeben werden. Dazu werden Sie beim Start der App aufgefordert."
ok thanks

2021-01-01 12:39 UTC, heinezen approved these changes

2021-01-01 12:40 UTC, heinezen commented
LGTM :)

2021-01-01 12:40 UTC, merged