FAQentry - Limit reached (replaces API39508)
corona-warn-app/cwa-website pull request #895
Opened 2021-02-16 10:46 UTC by heinezen

Alternative to https://github.com/corona-warn-app/cwa-website/pull/789

2021-02-16 11:03 UTC, MikeMcC399 commented on src/data/faq_de.json
> +                            "Dieser Fehler kann auftreten, wenn Sie die App zwischen 20:00 Uhr und 0:00 Uhr zurücksetzen und ihr Gerät den gesamten Tag über eine konstante WLAN-Verbindung hatte. Die
Suggest 0:00 Uhr => 00:00 Uhr
ihr Gerät => Ihr Gerät

2021-02-16 11:05 UTC, MikeMcC399 commented on src/data/faq.json
> +                            "The error should have disappeared by then and the your risk status should be displayed correctly.",
and the your risk status => and your risk status
or 
and your risk status should then

2021-02-16 11:09 UTC, MikeMcC399 commented on src/data/faq.json
> +                            "This error can occur if you reset the app between 20:00 and 0:00 and your device was constantly connected to Wifi for the whole day. The Corona-Warn-App has a daily limit
0:00 or 00:00?
Wifi => WiFi (or officially Wi-Fi)

2021-02-16 11:12 UTC, MikeMcC399 commented on src/data/faq_de.json
> +                            "<b>AKTUELL 16.01.2021</b><br/>Die Fehlermeldung lautet nun \"Limit bereits erreicht\". Bitte lesen Sie <a href='#delete_random_ids' target='_blank' rel='noopener'>den daz
#delete_random_ids => #limit_reached

2021-02-16 11:12 UTC, MikeMcC399 commented on src/data/faq.json
> +                            "<b>UPDATE 16.01.2021</b><br/>The error notification now reads \"Limit already reached\". Please see <a href='#delete_random_ids' target='_blank' rel='noopener'>the corres
#delete_random_ids => #limit_reached

2021-02-16 11:13 UTC, MikeMcC399 requested changes
Wrong link to `#limit_reached` otherwise just a few text suggestions for you.

2021-02-16 14:14 UTC, heinezen commented
@MikeMcC399 Thanks. All fixed :)

2021-02-16 15:30 UTC, MikeMcC399 approved these changes
LGTM 👍

2021-02-17 16:00 UTC, MikeMcC399 commented
This PR addresses issue #848.

2021-02-18 14:38 UTC, heinezen commented
@dsarkar Please check if we should also change the FAQ redirect for API39508 in here: https://github.com/corona-warn-app/cwa-website/blob/master/src/data/faq_redirects.json

2021-03-22 21:33 UTC, dsarkar commented
@MikeMcC399 @heinezen ok, thanks. We need to be careful with changing the anchor. We might brake links and also, I think that this FAQ entry with the old anchor is linked from the CWA when this error should occur. 

Option 1: Don't change anchor
Option 2: Redirect https://github.com/corona-warn-app/cwa-website/blob/2342931cc1fa68c538eb3d1a25fb6f74620233d7/src/data/faq_redirects.json

2021-03-23 13:51 UTC, heinezen commented
Option 2 is better I think, since the app then links to the appropriate FAQ entry

2021-03-23 15:16 UTC, MikeMcC399 commented
The app itself no longer links to any FAQ article. That is only is older versions.

The error message is now:

**Limit already reached**

"No more exposure checks possible today, as you have reached the maximum number of checks per day defined by your operating system. Please check your risk status again tomorrow."

I suggest to make a strategy decision about what versions of apps still need to have articles available to users. (I think that the current version and the previous version are all that is necessary, but you may think differently.)

The second point is about a policy decision whether to permanently provide a target destination for any URL that has ever been published. Because a published URL may have been written into a posting on GitHub, I believe it is always better to try not to leave a URL with a 404 file not found error. Again, you may think differently, but I think that there should continue to be a meaningful target for:
https://www.coronawarn.app/en/faq/#39508
https://www.coronawarn.app/en/faq/#API39508

If you want to continue to support old versions in the FAQ, then you should not change the link in the json file. Old apps will link to the old article with anchor #API39508 via anchor #39508.

If you decide not to support old versions in the FAQ, then you could remove all the text from the FAQ article #API39508, except for a link to the anchor #limit_reached.

2021-03-25 16:04 UTC, dsarkar commented
@MikeMcC399 @heinezen Latest info (1 minuet old) I have is: On the server the min. req. version iOS 1.5.3 and Android 1.0.4 **(!)**. There shouldn't be users with working CWA versions older than those mentioned, and all FAQ entries referring to < iOS 1.5.3 / Android 1.0.4 can be archived.

2021-05-03 12:17 UTC, MikeMcC399 approved these changes
@dsarkar 

Will you merge this PR now? I reviewed it again today and it looks good.

We have not had any new reports about this problem for some time now.

2021-05-03 12:21 UTC, merged

2021-05-03 12:22 UTC, dsarkar commented
@MikeMcC399 @heinezen Thanks!