Correct and Enhance `#qr_test`
corona-warn-app/cwa-website pull request #900
Opened 2021-02-19 08:19 UTC by Ein-Tim

This PR corrects wrong wording in `#qr_test` (#898) and enhances the entry to explain how to delete the test result before entering the TeleTAN (#899).

<details>
<summary>Screenshots of the changes</summary>

DE:
![image](https://user-images.githubusercontent.com/67682506/108477367-6bd7dd00-7293-11eb-99ac-3587c1ec1d13.png)

EN:
![image](https://user-images.githubusercontent.com/67682506/108477418-78f4cc00-7293-11eb-8378-833839636ece.png)

</details>

---

Closes #898 
Closes #899

2021-02-19 08:46 UTC, MikeMcC399 commented on src/data/faq_de.json
> +                            "Bestätigen Sie danach noch einmal das Sie den Test wirklich entfernen wollen. Nun können Sie die erfragte TeleTAN unter",
einmal das Sie => einmal, dass Sie

2021-02-19 08:51 UTC, Ein-Tim commented on src/data/faq_de.json
> +                            "Bestätigen Sie danach noch einmal das Sie den Test wirklich entfernen wollen. Nun können Sie die erfragte TeleTAN unter",
Corrected

2021-02-19 08:51 UTC, MikeMcC399 requested changes
In Android the labels:
DISPLAY TEST
DELETE TEST
NEXT STEPS
are displayed in upper case, so if this is different on iOS then choose either all upper case or all mixed cased for these labels (and their equivalent German names).

2021-02-19 08:52 UTC, Ein-Tim commented
@MikeMcC399 

Yes this differs from iOS, I will make all labels mixed cased.

2021-02-19 08:53 UTC, MikeMcC399 commented on src/data/faq_de.json
> +                            "Bestätigen Sie danach noch einmal, das Sie den Test wirklich entfernen wollen. Nun können Sie die erfragte TeleTAN unter",
einmal, das
should be
einmal, dass

2021-02-19 08:54 UTC, MikeMcC399 requested changes
This is about "einmal, dass"

https://www.duden.de/sprachwissen/sprachratgeber/das-oder-dass

2021-02-19 08:55 UTC, Ein-Tim commented on src/data/faq_de.json
> +                            "Bestätigen Sie danach noch einmal, das Sie den Test wirklich entfernen wollen. Nun können Sie die erfragte TeleTAN unter",
Corrected

2021-02-21 13:47 UTC, heinezen approved these changes
LGTM

2021-02-21 13:52 UTC, merged